import React, { createContext, useContext, useEffect, useMemo, useState } from 'react';

const LanguageContext = createContext({
  lang: 'fr',
  dir: 'ltr',
  toggle: () => {},
  t: (key) => key,
});

const translations = {
  fr: {
    'header.title': 'Portail de Signalement Anti-Corruption',
    'header.subtitle': 'Société des Ciments de Hamma Bouziane',
    'nav.home': 'Accueil',
    'nav.report': 'Poser une Plainte',
    'nav.policy': 'Politique',
    'nav.about': 'À propos',
    'nav.track': 'Signaler un cas de corruption',
    'toggle.toArabic': 'العربية',
    'toggle.toFrench': 'Français',

    'home.title': 'Portail Anti-Corruption',
    'home.welcome': 'Bienvenue sur la plateforme officielle de signalement des pratiques de corruption et de non-conformité.',
    'home.goal': "Notre objectif est de promouvoir l’intégrité, la transparence et l’éthique au sein de l’entreprise. Toute alerte reçue est traitée avec sérieux, impartialité et confidentialité.",
    'home.when.title': 'Quand utiliser ce portail ?',
    'home.when.li1': 'Conflits d’intérêts, fraude, corruption ou tentative de corruption.',
    'home.when.li2': 'Manipulation de données, falsification de documents, détournement de biens.',
    'home.when.li3': 'Non-respect des politiques internes et manquements à l’éthique.',
    'home.guarantees.title': 'Vos garanties',
    'home.guarantees.li1': 'Traitement confidentiel des signalements.',
    'home.guarantees.li2': 'Protection du lanceur d’alerte de bonne foi.',
    'home.guarantees.li3': 'Suivi transparent des étapes clés.',
    'home.cta.report': 'Poser un signalement',
    'home.cta.policy': 'Lire la politique',

    // Tracking page
    'track.badge': 'Suivi des signalements',
    'track.title': 'Suivi des signalements',
    'track.subtitle': 'Suivez l\'état de votre signalement à l\'aide du numéro reçu lors de l\'envoi.',
    'track.search.label': 'Rechercher un signalement',
    'track.search.placeholder': 'Numéro de suivi (ex: RPT-2024-001)',
    'track.search.button': 'Rechercher',
    'track.error.empty': 'Veuillez saisir un numéro de suivi.',
    'track.error.notFound': 'Numéro introuvable. Vérifiez et réessayez.',
    'track.status.received': 'Reçu et en cours de traitement',
    'track.result.id': 'Numéro de suivi :',
    'track.result.status': 'Statut :',
    'track.result.updated': 'Dernière mise à jour :',
    'track.how.title': 'Comment trouver le numéro de suivi ?',
    'track.how.p1': 'Le numéro de suivi vous a été communiqué lors de la soumission du signalement.',
    'track.how.li1': 'Email de confirmation reçu après l\'envoi.',
    'track.how.li2': 'Page de confirmation affichée après la soumission.',
    'track.how.li3': 'Conservez-le pour consulter l\'avancement.',
    'track.sample': 'Exemple :',
    'track.detail.title': 'Détails du signalement',
    'track.detail.type': 'Type',
    'track.detail.time': 'Date d\'enregistrement (DZ)',
    'track.detail.print': 'طباعة / Imprimer',
    'track.detail.download': 'Télécharger (PDF)',

    'userType.title': 'Je suis :',
    'userType.client': 'Client',
    'userType.client.desc': 'Vous êtes partenaire ou fournisseur de SCHB',
    'userType.employee': 'Employé',
    'userType.employee.desc': 'Vous êtes employé de SCHB',
    'userType.external': 'Externe',
    'userType.external.desc': 'Vous êtes visiter de SCHB',

    'report.chooseProfile': 'Veuillez choisir un profil pour continuer.',

    // Verification steps
    'verify.title': 'Vérification',
    'verify.step0.title': 'Étape 0 : Confidentialité',
    'verify.step0.p1': 'Veuillez télécharger et lire la Charte de Confidentialité « Charte de Recueil et Traitement de Signalement & de Protection de Lanceur d\'Alerte » avant de soumettre votre cas.',
    'verify.step0.p2': 'La plateforme n’est pas destinée à recevoir des réclamations, ni à soulever des problèmes liés aux ressources humaines. Pour ces problèmes, utilisez les canaux locaux appropriés.',
    'verify.step0.p3': 'Si vous souhaitez utiliser la plateforme pour signaler un cas, veuillez confirmer que vous avez lu et compris la politique, y compris la partie confidentialité.',
    'verify.confirm': 'Confirmer',
    'verify.continue': 'Continuer',
    'verify.close': 'Fermer',

    'verify.step1.title': 'Étape 1 : Saisissez votre adresse e-mail',
    'verify.step1.help': "Nous l'utiliserons pour vous envoyer un code de vérification.",
    'verify.email.label': 'Adresse e-mail :',
    'verify.send.code': 'Envoyer le code de vérification',
    'verify.back': 'Retour',

    'verify.step2.title': 'Étape 2 : Vérifiez le code de confirmation',
    'verify.code.label': 'Code de vérification :',
    'verify.captcha.label': 'Captcha :',
    'verify.captcha.input': 'Saisissez le captcha :',
    'verify.submit': 'Envoyer',

    'verify.error.email': 'Veuillez saisir une adresse e-mail valide.',
    'verify.info.sent': 'Un code de vérification a été envoyé à votre e-mail.',
    'verify.error.code': 'Code de vérification incorrect.',
    'verify.error.captcha': 'Captcha incorrect.',

    'footer.contacts': 'Coordonnées',
    'footer.dg': 'Direction Générale',
    'footer.up': 'Unité de Production',
    'footer.ucc': 'UC Constantine',
    'footer.uca': 'UC Annaba',
    'footer.ucs': 'UC Skikda',
    'footer.tel': '(Tel)',
    'footer.fax': '(Fax)',

    // Client form
    'client.title': 'Formulaire de Signalement - Client',
    'client.fullName': 'Nom Complet *',
    'client.company': 'Entreprise',
    'client.relation': 'Type de relation avec SCHB *',
    'client.relation.opt': 'Sélectionnez le type',
    'client.relation.clientDirect': 'Client direct',
    'client.relation.clientIndirect': 'Client indirect',
    'client.relation.distributor': 'Distributeur',
    'client.relation.retailer': 'Revendeur',
    'client.relation.other': 'Autre',
    'common.email': 'Email *',
    'common.phone': 'Téléphone',
    'client.orderNumber': 'Numéro de Commande',
    'common.incidentDateTime': "Date et heure de l'incident *",
    'client.department': 'Département concerné *',
    'client.department.opt': 'Sélectionnez un département',
    'dept.commercial': 'Commercial',
    'dept.logistique': 'Logistique',
    'dept.facturation': 'Facturation',
    'dept.qualite': 'Qualité',
    'dept.autre': 'Autre',
    'common.description': 'Description détaillée *',
    'client.description.ph': "Décrivez l'incident de corruption ou de fraude en détail...",
    'common.evidence': 'Preuves (documents, photos, etc.)',
    'client.submit': 'Soumettre le Signalement',

    // Employee form
    'employee.title': 'Formulaire de Signalement - Employé',
    'employee.matricule': 'Matricule',
    'employee.department': 'Département *',
    'employee.department.opt': 'Sélectionnez votre département',
    'dept.production': 'Production',
    'dept.maintenance': 'Maintenance',
    'dept.rh': 'Ressources Humaines',
    'dept.finance': 'Finance',
    'dept.achat': 'Achat',
    'employee.position': 'Poste',
    'employee.supervisor': 'Supérieur hiérarchique',
    'employee.location': "Lieu de l'incident *",
    'employee.persons': 'Personnes impliquées',
    'employee.persons.ph': 'Noms et postes des personnes concernées...',
    'employee.description.ph': "Décrivez en détail l'incident de corruption, fraude, ou inconduite...",
    'employee.evidence': 'Preuves (documents, emails, photos)',
    'employee.followup': 'Je souhaite un suivi de mon signalement',
    'employee.submit': 'Soumettre le Signalement Interne',

    // External form
    'external.title': 'Formulaire de Signalement - Partenaire/Fournisseur',
    'external.fullName': 'Nom Complet *',
    'external.incidentDept': 'Département SCHB concerné *',
    'external.incidentDept.opt': 'Sélectionnez un département',
    'dept.technique': 'Service Technique',
    'dept.direction': 'Direction',
    'external.persons': 'Personnes SCHB impliquées',
    'external.persons.ph': 'Noms et postes des employés SCHB concernés...',
    'external.description.ph': "Décrivez l'incident de corruption, demande de pot-de-vin, ou fraude...",
    'external.evidence': 'Preuves (documents, emails, enregistrements)',
    'external.submit': 'Soumettre le Signalement',

    // Success modal
    'success.title': 'Succès',
    'success.p1': 'Votre signalement a été soumis avec succès. Merci pour votre contribution.',
    'success.p2': 'Veuillez vérifier votre email après 24h.',
    'success.backHome': 'Retour à l’Accueil',
    'success.close': 'Fermer',
    'success.trackCode': 'Numéro de suivi',
    'success.savedAt': 'Enregistré le',
    'success.copyCode': 'Copier le code',
    'success.downloadQR': 'Télécharger le QR',
    'success.openTracking': 'Ouvrir le suivi',

    // Policy page
    'policy.title': 'POLITIQUE ANTI-CORRUPTION',
    'policy.intro': 'Société des Ciments de Hamma Bouziane (SCHB) - Groupe Industriel des Ciments d\'Algérie (GICA)',
    'policy.sectionTitle': 'Objectif de la politique',
    'policy.p1': "La SCHB s'engage à prévenir, détecter et combattre toute forme de corruption dans ses activités, en assurant une culture d'intégrité, de transparence et de conformité aux lois.",
    'policy.axesTitle': 'Axes stratégiques',
    'policy.axes.li1': 'Prévention : Sensibilisation, formation et mise en place de mécanismes de contrôle.',
    'policy.axes.li2': 'Détection : Systèmes d\'alerte et audits internes.',
    'policy.axes.li3': 'Sanction : Application rigoureuse des mesures disciplinaires en cas de violation.',
    'policy.commitmentsTitle': 'Engagements de la direction',
    'policy.commitments.li1': 'Tolérance zéro envers la corruption.',
    'policy.commitments.li2': 'Promotion de comportements éthiques.',
    'policy.commitments.li3': 'Renforcement des contrôles internes.',
    'policy.commitments.li4': 'Protection des lanceurs d\'alerte.',
    'policy.commitments.li5': 'Respect des lois nationales et internationales.',
    'policy.responsibilitiesTitle': 'Responsabilités des employés',
    'policy.responsibilities.li1': 'Refuser toute forme de pot-de-vin ou avantage indu.',
    'policy.responsibilities.li2': 'Signaler tout comportement suspect.',
    'policy.responsibilities.li3': 'Respecter les procédures internes.',
    'policy.responsibilities.li4': 'Participer aux formations sur l\'éthique et la conformité.',
    'policy.signature': 'Rabah Guessoum',
    'policy.position': 'Président Directeur Général – SCHB',

    // About page
    'about.title': 'À propos du système',
    'about.subtitle': 'Présentation du portail et de son objectif',
    'about.system.title': "Qu'est-ce que ce système ?",
    'about.system.p1': "Ce portail permet de signaler, en toute confidentialité, les cas de corruption, fraude et non-conformité au sein de l'entreprise.",
    'about.system.p2': "Les signalements sont traités avec sérieux, impartialité et dans le respect de la protection des lanceurs d'alerte.",
    'about.un_day.title': 'Journée internationale contre la corruption',
    'about.un_day.date': '9 décembre',
    'about.un_day.p1': "Cette journée, proclamée par l’ONU, vise à sensibiliser à l’importance de lutter contre la corruption et à promouvoir une culture d’intégrité.",
    'about.contact.p1': "Pour toute question, utilisez la page de politique ou contactez les canaux officiels de l’entreprise.",
    // General info sections
    'about.definition.title': 'Qu’est-ce que la corruption ?',
    'about.definition.p1': "Abus de pouvoir à des fins personnelles, comme la corruption (pots-de-vin), le détournement, ou le favoritisme.",
    'about.forms.title': 'Formes courantes',
    'about.forms.li1': 'Corruption et cadeaux inappropriés.',
    'about.forms.li2': 'Népotisme et favoritisme.',
    'about.forms.li3': 'Détournement de fonds et fausses factures.',
    'about.forms.li4': "Conflit d’intérêts.",
    'about.impacts.title': 'Impacts',
    'about.impacts.li1': 'Affaiblissement de la confiance dans les institutions.',
    'about.impacts.li2': 'Pertes économiques et frein au développement.',
    'about.impacts.li3': 'Injustice et inégalités.',
    'about.prevention.title': 'Prévention et intégrité',
    'about.prevention.li1': 'Transparence et divulgation.',
    'about.prevention.li2': 'Code de conduite et gestion des conflits d’intérêts.',
    'about.prevention.li3': 'Audit interne et formation.',
    'about.prevention.li4': 'Canaux de signalement sécurisés et protection des lanceurs d’alerte.',
    'about.reporting.title': 'Signalement responsable',
    'about.reporting.li1': 'Signaler en cas de soupçon raisonnable.',
    'about.reporting.li2': 'Inclure faits, dates et pièces justificatives si possibles.',
    'about.reporting.li3': 'Protection des lanceurs d’alerte de bonne foi.',
    'about.examples.title': 'Exemples concrets (résumés)',
    'about.examples.li1': "Un agent demande un cadeau pour accélérer un dossier → Refuser et signaler.",
    'about.examples.li2': "Employé attribue un marché à un proche sans concurrence → Conflit d’intérêts.",
    'about.examples.li3': "Factures gonflées contre une commission → Corruption et fraude.",
    'about.channels.title': 'Canaux de signalement',
    'about.channels.li1': 'Portail en ligne sécurisé (recommandé).',
    'about.channels.li2': 'Canaux internes dédiés (selon la politique).',
    'about.channels.li3': 'Voies supplémentaires selon la réglementation.',
  },
  ar: {
    'header.title': 'بوابة التبليغ عن الفساد',
    'header.subtitle': 'شركة إسمنت حمّة بوزيان',
    'nav.home': 'الصفحة الرئيسية',
    'nav.report': 'تقديم شكوى',
    'nav.policy': 'السياسة',
    'nav.about': 'حول النظام',
    'nav.track': 'متابعة التبليغ',
    'toggle.toArabic': 'Français',
    'toggle.toFrench': 'Français',
    
    // Policy page
    'policy.title': 'سياسة مكافحة الفساد',
    'policy.intro': 'شركة إسمنت حمة بوزيان (SCHB) - المجمع الصناعي للإسمنت بالجزائر (GICA)',
    'policy.sectionTitle': 'الغرض من السياسة',
    'policy.p1': 'تلتزم شركة SCHB بمنع وكشف ومكافحة جميع أشكال الفساد في أنشطتها، مع ضمان ثقافة النزاهة والشفافية والامتثال للقوانين.',
    'policy.axesTitle': 'المحاور الاستراتيجية',
    'policy.axes.li1': 'الوقاية: التوعية، التدريب، ووضع آليات رقابية.',
    'policy.axes.li2': 'الكشف: أنظمة إنذار ومراجعات داخلية.',
    'policy.axes.li3': 'العقوبات: تطبيق صارم للإجراءات التأديبية في حالة المخالفة.',
    'policy.commitmentsTitle': 'التزامات الإدارة',
    'policy.commitments.li1': 'عدم التسامح مطلقاً مع الفساد.',
    'policy.commitments.li2': 'تعزيز السلوكيات الأخلاقية.',
    'policy.commitments.li3': 'تعزيز الضوابط الداخلية.',
    'policy.commitments.li4': 'حماية المبلغين عن المخالفات.',
    'policy.commitments.li5': 'الالتزام بالقوانين المحلية والدولية.',
    'policy.responsibilitiesTitle': 'مسؤوليات الموظفين',
    'policy.responsibilities.li1': 'رفض أي شكل من أشكال الرشوة أو المنفعة غير المشروعة.',
    'policy.responsibilities.li2': 'الإبلاغ عن أي سلوك مشبوه.',
    'policy.responsibilities.li3': 'الالتزام بالإجراءات الداخلية.',
    'policy.responsibilities.li4': 'المشاركة في برامج التدريب حول الأخلاقيات والامتثال.',
    'policy.signature': 'الأستاذ رابح قسوم',
    'policy.position': 'المدير العام - شركة إسمنت حمة بوزيان',

    'home.title': 'بوابة مكافحة الفساد',
    'home.welcome': 'مرحبًا بكم في المنصة الرسمية للتبليغ عن ممارسات الفساد ومخالفة القوانين.',
    'home.goal': 'هدفنا هو تعزيز النزاهة والشفافية والأخلاق داخل المؤسسة. يتم التعامل مع كل بلاغ بجدية وحياد وسرية.',
    'home.when.title': 'متى تستخدم هذه البوابة؟',
    'home.when.li1': 'تعارض المصالح، الاحتيال، الفساد أو محاولة الفساد.',
    'home.when.li2': 'التلاعب بالبيانات، تزوير الوثائق، أو اختلاس الممتلكات.',
    'home.when.li3': 'عدم احترام السياسات الداخلية أو الإخلال بالأخلاق.',
    'home.guarantees.title': 'ضماناتكم',
    'home.guarantees.li1': 'معالجة سرية للبلاغات.',
    'home.guarantees.li2': 'حماية المُبلّغ حسن النية.',
    'home.guarantees.li3': 'متابعة شفافة للمراحل الرئيسية.',
    'home.cta.report': 'تقديم بلاغ',
    'home.cta.policy': 'قراءة السياسة',

    // Tracking page
    'track.badge': 'Suivi des signalements',
    'track.title': 'متابعة التبليغات',
    'track.subtitle': 'تتبّع حالة بلاغك باستخدام رقم المتابعة الذي تم تزويدك به عند الإرسال.',
    'track.search.label': 'البحث عن التبليغ',
    'track.search.placeholder': 'رقم المتابعة (مثال: RPT-2024-001)',
    'track.search.button': 'بحث',
    'track.error.empty': 'يرجى إدخال رقم المتابعة.',
    'track.error.notFound': 'لم يتم العثور على الرقم. تحقق ثم أعد المحاولة.',
    'track.status.received': 'تم الاستلام قيد المعالجة',
    'track.result.id': 'رقم المتابعة:',
    'track.result.status': 'الحالة:',
    'track.result.updated': 'آخر تحديث:',
    'track.how.title': 'كيفية العثور على رقم المتابعة؟',
    'track.how.p1': 'تم تزويدك برقم المتابعة عند تقديم البلاغ.',
    'track.how.li1': 'رسالة تأكيد إلى بريدك الإلكتروني بعد الإرسال.',
    'track.how.li2': 'الصفحة التأكيدية التي ظهرت بعد إرسال البلاغ.',
    'track.how.li3': 'احتفظ به للاطلاع على تقدم المعالجة.',
    'track.sample': 'مثال:',
    'track.detail.title': 'تفاصيل البلاغ',
    'track.detail.type': 'النوع',
    'track.detail.time': 'تاريخ التسجيل (الجزائر)',
    'track.detail.print': 'طباعة',
    'track.detail.download': 'تنزيل (PDF)',

    'userType.title': 'أنا:',
    'userType.client': 'زبون',
    'userType.client.desc': 'أنت شريك أو ممون لشركة SCHB',
    'userType.employee': 'موظف',
    'userType.employee.desc': 'أنت موظف في SCHB',
    'userType.external': 'خارجي',
    'userType.external.desc': 'أنت زائر لـ SCHB',

    'report.chooseProfile': 'يرجى اختيار نوع المستخدم للمتابعة.',

    // Verification steps
    'verify.title': 'التحقق',
    'verify.step0.title': 'الخطوة 0: السرية',
    'verify.step0.p1': 'يرجى تنزيل وقراءة ميثاق السرية « ميثاق جمع ومعالجة البلاغات وحماية المبلغين » قبل تقديم حالتك.',
    'verify.step0.p2': 'المنصة ليست مخصصة لتلقي الشكاوى أو المشاكل المتعلقة بالموارد البشرية. لهذه الأمور، استخدم القنوات المحلية المناسبة.',
    'verify.step0.p3': 'إذا كنت ترغب في استخدام المنصة للإبلاغ، يرجى تأكيد أنك قرأت وفهمت السياسة بما في ذلك جزء السرية.',
    'verify.confirm': 'تأكيد',
    'verify.continue': 'متابعة',
    'verify.close': 'إغلاق',

    'verify.step1.title': 'الخطوة 1: أدخل بريدك الإلكتروني',
    'verify.step1.help': 'سنستخدمه لإرسال رمز تحقق إليك.',
    'verify.email.label': 'البريد الإلكتروني:',
    'verify.send.code': 'إرسال رمز التحقق',
    'verify.back': 'رجوع',

    'verify.step2.title': 'الخطوة 2: تحقق من رمز التأكيد',
    'verify.code.label': 'رمز التحقق:',
    'verify.captcha.label': 'كابتشا:',
    'verify.captcha.input': 'أدخل الكابتشا:',
    'verify.submit': 'إرسال',

    'verify.error.email': 'يرجى إدخال بريد إلكتروني صالح.',
    'verify.info.sent': 'تم إرسال رمز تحقق إلى بريدك الإلكتروني.',
    'verify.error.code': 'رمز التحقق غير صحيح.',
    'verify.error.captcha': 'كابتشا غير صحيح.',

    'footer.contacts': 'بيانات الاتصال',
    'footer.dg': 'المديرية العامة',
    'footer.up': 'وحدة الإنتاج',
    'footer.ucc': 'وحدة قسنطينة',
    'footer.uca': 'وحدة عنابة',
    'footer.ucs': 'وحدة سكيكدة',
    'footer.tel': '(هاتف)',
    'footer.fax': '(فاكس)',

    // Client form
    'client.title': 'نموذج الإبلاغ - زبون',
    'client.fullName': 'الاسم الكامل *',
    'client.company': 'المؤسسة',
    'client.relation': 'نوع العلاقة مع SCHB *',
    'client.relation.opt': 'اختر النوع',
    'client.relation.clientDirect': 'زبون مباشر',
    'client.relation.clientIndirect': 'زبون غير مباشر',
    'client.relation.distributor': 'موزع',
    'client.relation.retailer': 'بائع',
    'client.relation.other': 'أخرى',
    'common.email': 'البريد الإلكتروني *',
    'common.phone': 'الهاتف',
    'client.orderNumber': 'رقم الطلب',
    'common.incidentDateTime': 'تاريخ ووقت الحادثة *',
    'client.department': 'القسم المعني *',
    'client.department.opt': 'اختر قسماً',
    'dept.commercial': 'التجاري',
    'dept.logistique': 'اللوجستيك',
    'dept.facturation': 'الفوترة',
    'dept.qualite': 'الجودة',
    'dept.autre': 'أخرى',
    'common.description': 'وصف مفصل *',
    'client.description.ph': 'صف الحادثة المتعلقة بالفساد أو الاحتيال بالتفصيل...',
    'common.evidence': 'أدلة (مستندات، صور، ...)',
    'client.submit': 'إرسال البلاغ',

    // Employee form
    'employee.title': 'نموذج الإبلاغ - موظف',
    'employee.matricule': 'الرقم الوظيفي',
    'employee.department': 'القسم *',
    'employee.department.opt': 'اختر قسمك',
    'dept.production': 'الإنتاج',
    'dept.maintenance': 'الصيانة',
    'dept.rh': 'الموارد البشرية',
    'dept.finance': 'المالية',
    'dept.achat': 'الشراء',
    'employee.position': 'المنصب',
    'employee.supervisor': 'الرئيس المباشر',
    'employee.location': 'مكان الحادثة *',
    'employee.persons': 'الأشخاص المعنيون',
    'employee.persons.ph': 'أسماء ومناصب الأشخاص المعنيين...',
    'employee.description.ph': 'صف بالتفصيل حادثة الفساد أو الاحتيال أو السلوك...',
    'employee.evidence': 'أدلة (مستندات، بريد إلكتروني، صور)',
    'employee.followup': 'أرغب في متابعة بلاغي',
    'employee.submit': 'إرسال البلاغ الداخلي',

    // External form
    'external.title': 'نموذج الإبلاغ - شريك/مموّن',
    'external.fullName': 'الاسم الكامل *',
    'external.incidentDept': 'قسم SCHB المعني *',
    'external.incidentDept.opt': 'اختر قسماً',
    'dept.technique': 'الخدمة التقنية',
    'dept.direction': 'الإدارة',
    'external.persons': 'موظفو SCHB المعنيون',
    'external.persons.ph': 'أسماء ومناصب موظفي SCHB المعنيين...',
    'external.description.ph': 'صف حادثة الفساد أو طلب الرشوة أو الاحتيال...',
    'external.evidence': 'أدلة (مستندات، بريد إلكتروني، تسجيلات)',
    'external.submit': 'إرسال البلاغ',

    // Success modal
    'success.title': 'نجاح',
    'success.p1': 'تم إرسال بلاغك بنجاح. شكراً لمساهمتك.',
    'success.p2': 'يرجى التحقق من بريدك الإلكتروني بعد 24 ساعة.',
    'success.backHome': 'العودة إلى الرئيسية',
    'success.close': 'إغلاق',
    'success.trackCode': 'رقم المتابعة',
    'success.savedAt': 'تم الحفظ بتاريخ',
    'success.copyCode': 'نسخ الكود',
    'success.downloadQR': 'تحميل QR',
    'success.openTracking': 'فتح صفحة المتابعة',

    // Policy page
    'policy.title': 'سياسة مكافحة الفساد',
    'policy.intro': 'معلومات حول سياسة مكافحة الفساد لدى SCHB.',
    'policy.sectionTitle': 'التزام شركة SCHB',
    'policy.p1': 'تلتزم SCHB بالحفاظ على معايير أخلاقية عالية من النزاهة والشفافية والامتثال، ومكافحة جميع أشكال الفساد في عملياتها.',
    'policy.p2': 'تنطبق هذه السياسة على جميع الموظفين والشركاء والمموّنين وتشمل على وجه الخصوص:',
    'policy.li1': 'الوقاية من تضارب المصالح والهدايا غير المناسبة.',
    'policy.li2': 'الإبلاغ عن السلوكيات المشبوهة عبر قنوات آمنة.',
    'policy.li3': 'تكوين وتوعية الفرق بشكل منتظم.',
    'policy.li4': 'الالتزام بالقوانين والأنظمة المعمول بها.',

    // About page
    'about.title': 'حول النظام',
    'about.subtitle': 'تعريف بالبوابة وهدفها',
    'about.system.title': 'ما هو هذا النظام؟',
    'about.system.p1': 'هذه البوابة تمكّن من التبليغ بسرية عن حالات الفساد والاحتيال ومخالفة القوانين داخل المؤسسة.',
    'about.system.p2': 'تتم معالجة البلاغات بجدية وحياد، مع احترام حماية المبلّغين.',
    'about.un_day.title': 'اليوم العالمي لمكافحة الفساد',
    'about.un_day.date': '9 ديسمبر',
    'about.un_day.p1': 'أقرّته الأمم المتحدة لرفع الوعي بأهمية مكافحة الفساد وتعزيز ثقافة النزاهة.',
    'about.contact.p1': 'لأي استفسار، راجع صفحة السياسة أو اتصل بالقنوات الرسمية للمؤسسة.',
    // General info sections
    'about.definition.title': 'ما هو الفساد؟',
    'about.definition.p1': 'استعمال غير مشروع للسلطة لتحقيق منفعة شخصية مثل الرشوة، الاختلاس، أو المحاباة.',
    'about.forms.title': 'أشكال شائعة',
    'about.forms.li1': 'الرشوة والهدايا غير المناسبة.',
    'about.forms.li2': 'المحسوبية والمحاباة.',
    'about.forms.li3': 'اختلاس الأموال وفواتير وهمية أو مضخّمة.',
    'about.forms.li4': 'تضارب المصالح.',
    'about.impacts.title': 'الآثار',
    'about.impacts.li1': 'إضعاف الثقة بالمؤسسات.',
    'about.impacts.li2': 'خسائر اقتصادية وتعطيل التنمية.',
    'about.impacts.li3': 'ظلم وعدم مساواة.',
    'about.prevention.title': 'الوقاية والنزاهة',
    'about.prevention.li1': 'الشفافية والإفصاح.',
    'about.prevention.li2': 'مدونة سلوك وإدارة تضارب المصالح.',
    'about.prevention.li3': 'تدقيق داخلي وتدريب.',
    'about.prevention.li4': 'قنوات تبليغ آمنة وحماية المبلّغين.',
    'about.reporting.title': 'التبليغ المسؤول',
    'about.reporting.li1': 'يتم التبليغ عند وجود اشتباه معقول.',
    'about.reporting.li2': 'يتضمن البلاغ وقائع وتواريخ ووثائق إن أمكن.',
    'about.reporting.li3': 'حماية المبلّغين حسني النية.',
    'about.examples.title': 'أمثلة واقعية مختصرة',
    'about.examples.li1': 'موظف يطلب هدية لتسريع معاملة → رفض والتبليغ.',
    'about.examples.li2': 'إسناد صفقة لقريب دون منافسة → تضارب مصالح.',
    'about.examples.li3': 'تضخيم فواتير مقابل عمولة → فساد واحتيال.',
  }
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('lang') || 'fr');
  const dir = lang === 'ar' ? 'rtl' : 'ltr';

  useEffect(() => {
    document.documentElement.setAttribute('lang', lang);
    document.documentElement.setAttribute('dir', dir);
    localStorage.setItem('lang', lang);
  }, [lang, dir]);

  const t = useMemo(() => {
    const table = translations[lang] || translations.fr;
    return (key) => table[key] ?? key;
  }, [lang]);

  const value = useMemo(() => ({
    lang,
    dir,
    toggle: () => setLang((prev) => (prev === 'fr' ? 'ar' : 'fr')),
    t,
  }), [lang, dir, t]);

  return (
    <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
